[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]

name = "occ_climate"
version = "0.0.8"
authors = [
 { name="Jerry Liu", email="write874260@gmail.com" },
 {name= "Dr. Rebecca Beadling", email= "rebecca.beadling@temple.edu"}
]
description = "function of Ocean Climate Connections (OCC) Research Group at Temple University!"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

license = { file = "LICENSE" }

[tool.setuptools]
license-files = []

[project.urls]
Homepage = "https://github.com/occ-research/occ_package_test.git"
Issues = "https://github.com/occ-research/occ_package_test.git/issues"

